#!/bin/bash
VERSION="1"

. /usr/share/univention-lib/ldap.sh
. /usr/share/univention-appcenter/joinscripthelper.sh

joinscript_init

eval "$(ucr shell)"
SERVICE="Kopano-Konnect"
APP="openid-connect-provider"

ucs_removeServiceFromLocalhost "${SERVICE}" "$@"

rm -f /etc/apache2/ucs-sites.conf.d/openid-connect-provider.conf
invoke-rc.d apache2 reload

# remove udm module
ucs_unregisterLDAPExtension "$@" \
	--schema openid-connect-provider \
	--udm_module oidc/rpservice \
	--acl 58openid-connect-provider.ldapacl || die

udm saml/serviceprovider remove --dn "SAMLServiceProviderIdentifier=openid-connect-provider,cn=saml-serviceprovider,cn=univention,${ldap_base}"

# remove listener module
rm -f /usr/lib/univention-directory-listener/system/openid-connect-provider-listener.py
service univention-directory-listener restart

rm -r /usr/share/univention-openid-connect-provider/

joinscript_remove_script_from_status_file "$APP"
exit 0
